-- ArcadeDB schema definition for EcoNest
-- Issue #4

-- ============================================================
-- Vertex types
-- ============================================================
CREATE VERTEX TYPE Home IF NOT EXISTS;
CREATE PROPERTY Home.name IF NOT EXISTS STRING;
CREATE PROPERTY Home.address IF NOT EXISTS STRING;
CREATE PROPERTY Home.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Room IF NOT EXISTS;
CREATE PROPERTY Room.name IF NOT EXISTS STRING;
CREATE PROPERTY Room.room_type IF NOT EXISTS STRING;  -- Bedroom, Kitchen, Garage, LivingRoom
CREATE PROPERTY Room.description IF NOT EXISTS STRING;
CREATE PROPERTY Room.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Device IF NOT EXISTS;
CREATE PROPERTY Device.name IF NOT EXISTS STRING;
CREATE PROPERTY Device.device_type IF NOT EXISTS STRING;  -- SmartPlug, SmartBulb, MotionSensor, ...
CREATE PROPERTY Device.ha_entity_id IF NOT EXISTS STRING;
CREATE PROPERTY Device.ip_address IF NOT EXISTS STRING;
CREATE PROPERTY Device.is_active IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Device.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Circuit IF NOT EXISTS;
CREATE PROPERTY Circuit.name IF NOT EXISTS STRING;
CREATE PROPERTY Circuit.breaker_id IF NOT EXISTS STRING;
CREATE PROPERTY Circuit.max_amperage IF NOT EXISTS FLOAT;
CREATE PROPERTY Circuit.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Sensor IF NOT EXISTS;
CREATE PROPERTY Sensor.name IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.sensor_type IF NOT EXISTS STRING;  -- motion, sound, power, temperature
CREATE PROPERTY Sensor.unit IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE User IF NOT EXISTS;
CREATE PROPERTY User.email IF NOT EXISTS STRING;
CREATE PROPERTY User.role IF NOT EXISTS STRING;
CREATE PROPERTY User.is_active IF NOT EXISTS BOOLEAN;
CREATE PROPERTY User.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Capability IF NOT EXISTS;
CREATE PROPERTY Capability.name IF NOT EXISTS STRING;
CREATE PROPERTY Capability.description IF NOT EXISTS STRING;

CREATE VERTEX TYPE Action IF NOT EXISTS;
CREATE PROPERTY Action.name IF NOT EXISTS STRING;
CREATE PROPERTY Action.parameters IF NOT EXISTS MAP;
CREATE PROPERTY Action.timestamp IF NOT EXISTS DATETIME;

-- ============================================================
-- Edge types
-- ============================================================
CREATE EDGE TYPE CONTAINS IF NOT EXISTS;
CREATE PROPERTY CONTAINS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE POWERED_BY IF NOT EXISTS;
CREATE PROPERTY POWERED_BY.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE MONITORS IF NOT EXISTS;
CREATE PROPERTY MONITORS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE OWNS IF NOT EXISTS;
CREATE PROPERTY OWNS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE HAS_ACCESS IF NOT EXISTS;
CREATE PROPERTY HAS_ACCESS.permission IF NOT EXISTS STRING;
CREATE PROPERTY HAS_ACCESS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE CAN_PERFORM IF NOT EXISTS;
CREATE PROPERTY CAN_PERFORM.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE HAS_CAPABILITY IF NOT EXISTS;
CREATE PROPERTY HAS_CAPABILITY.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE REQUIRES_CAPABILITY IF NOT EXISTS;
CREATE PROPERTY REQUIRES_CAPABILITY.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE DEPENDS_ON IF NOT EXISTS;
CREATE PROPERTY DEPENDS_ON.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE LOCATED_IN IF NOT EXISTS;
CREATE PROPERTY LOCATED_IN.created_at IF NOT EXISTS DATETIME;

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS ON User(email) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Room(name) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON Device(name) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON Device(ha_entity_id) UNIQUE;
