-- ArcadeDB schema definition for EcoNest
-- Issue #4

-- ============================================================
-- Vertex types
-- ============================================================
CREATE VERTEX TYPE Home IF NOT EXISTS;
CREATE PROPERTY Home.name IF NOT EXISTS STRING;
CREATE PROPERTY Home.address IF NOT EXISTS STRING;
CREATE PROPERTY Home.home_assistant_url IF NOT EXISTS STRING;
CREATE PROPERTY Home.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Room IF NOT EXISTS;
CREATE PROPERTY Room.mysql_id IF NOT EXISTS INTEGER;
CREATE PROPERTY Room.name IF NOT EXISTS STRING;
CREATE PROPERTY Room.room_type IF NOT EXISTS STRING;  -- Bedroom, Kitchen, Garage, LivingRoom
CREATE PROPERTY Room.description IF NOT EXISTS STRING;
CREATE PROPERTY Room.ha_area_id IF NOT EXISTS STRING;
CREATE PROPERTY Room.floor_id IF NOT EXISTS STRING;
CREATE PROPERTY Room.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Device IF NOT EXISTS;
CREATE PROPERTY Device.mysql_id IF NOT EXISTS INTEGER;
CREATE PROPERTY Device.name IF NOT EXISTS STRING;
CREATE PROPERTY Device.device_type IF NOT EXISTS STRING;  -- EnergyMonitor, SmartPlug, SmartBulb, MotionSensor, ...
CREATE PROPERTY Device.ha_domain IF NOT EXISTS STRING;
CREATE PROPERTY Device.ha_entity_id IF NOT EXISTS STRING;
CREATE PROPERTY Device.ha_device_id IF NOT EXISTS STRING;
CREATE PROPERTY Device.ha_area_id IF NOT EXISTS STRING;
CREATE PROPERTY Device.ha_platform IF NOT EXISTS STRING;
CREATE PROPERTY Device.manufacturer IF NOT EXISTS STRING;
CREATE PROPERTY Device.model IF NOT EXISTS STRING;
CREATE PROPERTY Device.ip_address IF NOT EXISTS STRING;
CREATE PROPERTY Device.via_device_id IF NOT EXISTS STRING;
CREATE PROPERTY Device.is_active IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Device.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Circuit IF NOT EXISTS;
CREATE PROPERTY Circuit.name IF NOT EXISTS STRING;
CREATE PROPERTY Circuit.breaker_id IF NOT EXISTS STRING;
CREATE PROPERTY Circuit.max_amperage IF NOT EXISTS FLOAT;
CREATE PROPERTY Circuit.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Sensor IF NOT EXISTS;
CREATE PROPERTY Sensor.name IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.sensor_type IF NOT EXISTS STRING;  -- motion, sound, power, temperature
CREATE PROPERTY Sensor.unit IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.ha_entity_id IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.device_class IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.state_class IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE SensorReading IF NOT EXISTS;
CREATE PROPERTY SensorReading.mysql_id IF NOT EXISTS LONG;
CREATE PROPERTY SensorReading.device_id IF NOT EXISTS INTEGER;
CREATE PROPERTY SensorReading.room_id IF NOT EXISTS INTEGER;
CREATE PROPERTY SensorReading.timestamp IF NOT EXISTS DATETIME;
CREATE PROPERTY SensorReading.data IF NOT EXISTS MAP;

CREATE VERTEX TYPE User IF NOT EXISTS;
CREATE PROPERTY User.email IF NOT EXISTS STRING;
CREATE PROPERTY User.role IF NOT EXISTS STRING;
CREATE PROPERTY User.household_id IF NOT EXISTS INTEGER;
CREATE PROPERTY User.is_active IF NOT EXISTS BOOLEAN;
CREATE PROPERTY User.created_at IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Capability IF NOT EXISTS;
CREATE PROPERTY Capability.name IF NOT EXISTS STRING;
CREATE PROPERTY Capability.description IF NOT EXISTS STRING;

CREATE VERTEX TYPE Action IF NOT EXISTS;
CREATE PROPERTY Action.name IF NOT EXISTS STRING;
CREATE PROPERTY Action.parameters IF NOT EXISTS MAP;
CREATE PROPERTY Action.timestamp IF NOT EXISTS DATETIME;

CREATE VERTEX TYPE Observation IF NOT EXISTS;
CREATE PROPERTY Observation.observation_type IF NOT EXISTS STRING;
CREATE PROPERTY Observation.value IF NOT EXISTS STRING;
CREATE PROPERTY Observation.confidence IF NOT EXISTS FLOAT;
CREATE PROPERTY Observation.source_sensor IF NOT EXISTS STRING;
CREATE PROPERTY Observation.timestamp IF NOT EXISTS DATETIME;
CREATE PROPERTY Observation.context IF NOT EXISTS MAP;

CREATE VERTEX TYPE Query IF NOT EXISTS;
CREATE PROPERTY Query.text IF NOT EXISTS STRING;
CREATE PROPERTY Query.timestamp IF NOT EXISTS DATETIME;
CREATE PROPERTY Query.intent IF NOT EXISTS STRING;
CREATE PROPERTY Query.context IF NOT EXISTS MAP;

CREATE VERTEX TYPE Response IF NOT EXISTS;
CREATE PROPERTY Response.text IF NOT EXISTS STRING;
CREATE PROPERTY Response.timestamp IF NOT EXISTS DATETIME;
CREATE PROPERTY Response.summary IF NOT EXISTS STRING;

CREATE VERTEX TYPE MemorySummary IF NOT EXISTS;
CREATE PROPERTY MemorySummary.summary_text IF NOT EXISTS STRING;
CREATE PROPERTY MemorySummary.created_at IF NOT EXISTS DATETIME;
CREATE PROPERTY MemorySummary.time_window IF NOT EXISTS STRING;

-- ============================================================
-- Edge types
-- ============================================================
CREATE EDGE TYPE CONTAINS IF NOT EXISTS;
CREATE PROPERTY CONTAINS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE POWERED_BY IF NOT EXISTS;
CREATE PROPERTY POWERED_BY.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE MONITORS IF NOT EXISTS;
CREATE PROPERTY MONITORS.created_at IF NOT EXISTS DATETIME;
-- For confidence scores
CREATE PROPERTY MONITORS.confidence_score IF NOT EXISTS FLOAT;

CREATE EDGE TYPE OWNS IF NOT EXISTS;
CREATE PROPERTY OWNS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE HAS_ACCESS IF NOT EXISTS;
CREATE PROPERTY HAS_ACCESS.permission IF NOT EXISTS STRING;
CREATE PROPERTY HAS_ACCESS.allowed_start_hour IF NOT EXISTS INTEGER;
CREATE PROPERTY HAS_ACCESS.allowed_end_hour IF NOT EXISTS INTEGER;
CREATE PROPERTY HAS_ACCESS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE CAN_PERFORM IF NOT EXISTS;
CREATE PROPERTY CAN_PERFORM.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE HAS_CAPABILITY IF NOT EXISTS;
CREATE PROPERTY HAS_CAPABILITY.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE REQUIRES_CAPABILITY IF NOT EXISTS;
CREATE PROPERTY REQUIRES_CAPABILITY.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE DEPENDS_ON IF NOT EXISTS;
CREATE PROPERTY DEPENDS_ON.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE LOCATED_IN IF NOT EXISTS;
CREATE PROPERTY LOCATED_IN.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE OBSERVED_IN IF NOT EXISTS;
CREATE PROPERTY OBSERVED_IN.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE DERIVED_FROM IF NOT EXISTS;
CREATE PROPERTY DERIVED_FROM.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE SUMMARIZES IF NOT EXISTS;
CREATE PROPERTY SUMMARIZES.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE REMEMBERS IF NOT EXISTS;
CREATE PROPERTY REMEMBERS.created_at IF NOT EXISTS DATETIME;

CREATE EDGE TYPE REFERENCED_OBSERVATION IF NOT EXISTS;
CREATE PROPERTY REFERENCED_OBSERVATION.created_at IF NOT EXISTS DATETIME;

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS ON User(email) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Home(name) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Room(mysql_id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Room(name) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON Room(ha_area_id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Device(mysql_id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Device(name) NOTUNIQUE;
CREATE INDEX IF NOT EXISTS ON Device(ha_entity_id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Sensor(ha_entity_id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON SensorReading(mysql_id) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Observation(source_sensor) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Capability(name) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Action(name) UNIQUE;
CREATE INDEX IF NOT EXISTS ON Circuit(breaker_id) UNIQUE;
